### ISSUE TITLE
I forked this

### ISSUE THREAD

**Issue by deisi** [mib4fun/docker-spotifyd#1]
Hey, I forked this repo for a little project of mine. The goal is to simplify the setup multiroom audio system. 

There was/is no licence in your project. Would you be fine with me adding MIT licence to my project that currently contains your contributions? If not I would remove your contributions.

https://github.com/deisi/audiostation-spotify this is my fork by the way

**Comment by jvkassi** [comment]
Hello,

Thanks for the contribution. Right i will add a MIT license

**Comment by jvkassi** [comment]
i haved added the MIT.

Closing issue
